import type { Book, Collection, Entry, SourceFile, SourceKey } from "./types";

const ANDO = "/media/ando";

/**
 * Seed catalog for Oshiwambo Shookuku.
 *
 * Derived from the preview’s src/data/catalog.ts (26 September 2026) and
 * checked line by line against docs/source. See
 * docs/content-audit-2026-09-26.md for every change.
 *
 * Rule: short, attributed teasers only. No full procedures. No invented steps.
 */

export const site = {
  name: "Oshiwambo Shookuku",
  domain: "oshiwamboshookuku.com",
  url: "https://oshiwamboshookuku.com",
  author: "Professor Petrus Angula Mbenzi",
  line: "Moshinkoti shookuku",
  lineEn: "In the footsteps of our ancestors",
  org: "Tameka-AI",
  coreBook: "Omuthigululwakalo gwAawambo ohela nonena",
} as const;

export const sources: Record<SourceKey, SourceFile> = {
  description: { file: "The-description-of-Aawambo-2026.md", title: "The description of Aawambo 2026" },
  rituals: { file: "Oshiwambo-rituals-and-ceremonies.md", title: "Oshiwambo rituals and ceremonies" },
  homestead: { file: "The-OshiwamboTraditional-Homestead.md", title: "The Oshiwambo Traditional Homestead" },
  marriage: {
    file: "pre-maarriage-marriage-and-post-marriage-customs-and-rules.md",
    title: "Pre-marriage, marriage and post-marriage customs and rules",
  },
  kinship: {
    file: "Kinship-terms-and-customs-and-Clan-System.md",
    title: "Kinship terms and customs and Clan System",
  },
  ethnobotany: { file: "Aawambo-Ethnobotany.md", title: "Aawambo Ethnobotany" },
  greetings: { file: "OSHIWAMBO-FORMS-OF-GREETING.md", title: "Oshiwambo forms of greeting" },
};

/** From “The description of Aawambo 2026”, in the author’s order. */
export const dialects: readonly string[] = [
  "Oshindonga",
  "Oshikwanyama",
  "Oshikwambi",
  "Oshingandjera",
  "Oshikwaluudhi",
  "Oshikolonkadhi",
  "Oshimbalantu",
  "Oshiunda",
  "Oshimbadja",
  "Oshikwankwa",
  "Oshivale",
  "Oshindongona",
  "Oshikafima",
  "Oshindombodhola",
];

export const people = {
  summary:
    "Aawambo are Bantu-speaking people of northern Namibia and southern Angola. Their language cluster, Oshiwambo, has fourteen mutually intelligible dialects.",
  censusNote:
    "The author cites the 2023 Population and Housing Census: the Aawambo make up approximately half of Namibia’s population.",
  source: "description" as SourceKey,
};

export const collections: Collection[] = [
  {
    slug: "lifecycle",
    title: "A life, from first breath to remembrance",
    blurb:
      "Initiation, naming, twins, healing, new harvest, cattle festival, mourning, and the move to a new house — the spine of the core book.",
    source: "rituals",
    sourceCount: { n: 17, unit: "ceremonies" },
    image: "/media/kraal.jpg",
    tone: "clay",
  },
  {
    slug: "homestead",
    title: "The traditional homestead",
    osh: "Egumbo",
    blurb:
      "Fourteen places inside the palisade: the eastern gate, the meeting fire, the kitchen, the birthing hut, granaries, and the cattle kraal.",
    source: "homestead",
    sourceCount: { n: 14, unit: "places" },
    image: "/media/homestead.jpg",
    tone: "sand",
  },
  {
    slug: "marriage",
    title: "Before, during, and after marriage",
    blurb:
      "Clan exogamy, preferred and discouraged unions, and how a new household is seated among the Aawambo.",
    source: "marriage",
    image: "/media/marula.jpg",
    tone: "ochre",
  },
  {
    slug: "kinship",
    title: "Kinship, clans, and address",
    blurb:
      "How people name mother, father, grandparents, and clan — and why a clan father still matters in justice and belonging.",
    source: "kinship",
    image: "/media/basket.jpg",
    tone: "dusk",
  },
  {
    slug: "plants",
    title: "Trees that hold a household",
    blurb:
      "Omugolo for return and protection. Omusati, the mopane, for peace in a new dwelling. Ekaka and omboga as signs of unity.",
    source: "ethnobotany",
    image: "/media/mopane.jpg",
    tone: "moss",
  },
  {
    slug: "greetings",
    title: "How a day is greeted",
    blurb:
      "Morning through evening, a visitor at the gate, the royal house, Christmas and the new year, and the poetry inside ordinary speech.",
    source: "greetings",
    sourceCount: { n: 13, unit: "greeting situations" },
    image: "/media/hearth.jpg",
    tone: "ash",
  },
];

export const entries: Entry[] = [
  // ── Lifecycle ────────────────────────────────────────────────────────────
  {
    id: "initiation",
    title: "Initiation of girls",
    osh: "Efundula / olufuko",
    collection: "lifecycle",
    status: "unspecified",
    summary:
      "Before marriage, grown girls enrol for efundula at Namunganga’s house, accompanied by their mothers. The ceremony runs over four named days. The full sequence stays with the author’s text.",
    who: "Girls before marriage, their mothers, Namunganga",
    when: "Before marriage, over four days",
    where: "Namunganga’s homestead",
    why: "To prepare girls for marriage and adult life.",
    sources: ["rituals"],
    image: "/media/kraal.jpg",
    tone: "clay",
  },
  {
    id: "naming",
    title: "Naming a child",
    collection: "lifecycle",
    status: "unspecified",
    summary:
      "The author’s files hold two accounts side by side. In the homestead paper the midwife seats the child in the birthing hut and gives a name that reflects the arrival. In the ritual record the father announces the name. Bark rings of omugolo were once tied on newborns.",
    who: "Midwife, mother, father",
    when: "From the first days after birth",
    where: "Osakalwa, the birthing hut, and the mother’s hut",
    why: "A name places the child in the story of the house.",
    sources: ["rituals", "homestead", "ethnobotany"],
    image: "/media/hearth.jpg",
    tone: "ochre",
  },
  {
    id: "twins",
    title: "The birth of twins",
    collection: "lifecycle",
    status: "unspecified",
    summary:
      "The record describes the birth of twins as a bad omen, answered apart from an ordinary birth: the mother is moved with her babies to a hut built for her in the mahangu field. The platform will hold the procedure only as the author releases it.",
    who: "Mother, traditional healer, paternal and maternal clans",
    when: "At a twin birth",
    where: "A hut in the mahangu field",
    why: "The household must answer a double arrival correctly.",
    sources: ["rituals"],
    image: "/media/homestead.jpg",
    tone: "sand",
  },
  {
    id: "oshipe",
    title: "Eating the new harvest",
    osh: "Oshipe",
    collection: "lifecycle",
    status: "unspecified",
    summary:
      "After winnowing, the household holds a thanksgiving for the harvest. The first tasting of the new mahangu is a ceremony, not a meal, and the ancestors are given their share first.",
    who: "Household and community",
    when: "After winnowing the new crop",
    where: "Homestead",
    why: "No one eats the new food before the house has marked it.",
    sources: ["rituals"],
    image: "/media/marula.jpg",
    tone: "ochre",
  },
  {
    id: "cattle",
    title: "Cattle festival",
    osh: "Oshidhano shoongombe",
    collection: "lifecycle",
    status: "living",
    statusBasis:
      "It has to be pointed out Omaludi eengobe is now practiced with vibrancy and is even recognized by modern authorities",
    summary:
      "Omaludi eengobe — a public festival of cattle, with dance and display, held at the end of April after the rains. Well-kept herds are honoured, and herders are urged to do better at the next gathering.",
    who: "Herders, household, neighbours",
    when: "End of April, after the rains",
    where: "Kraal and open ground",
    why: "To encourage herders, so the cattle give milk and butter to the household.",
    sources: ["rituals"],
    image: "/media/kraal.jpg",
    tone: "clay",
  },
  {
    id: "omitima",
    title: "The heart feast",
    osh: "Omitima",
    collection: "lifecycle",
    status: "living",
    statusBasis: "This feast is enjoyed by several Aawambo even today.",
    summary:
      "One of four meat feasts recorded beside the intestine, lung, and hump feasts. When a man kills an ox, the heart feast is how he honours a parallel cousin of his clan.",
    who: "Parallel cousins of the same clan",
    when: "After an ox is slaughtered",
    where: "Homestead",
    why: "It keeps the tie between parallel cousins alive.",
    sources: ["rituals"],
    image: "/media/hearth.jpg",
    tone: "dusk",
  },
  {
    id: "mourning",
    title: "Mourning",
    collection: "lifecycle",
    status: "unspecified",
    summary:
      "Death closes a life inside a set period of mourning — shorter for a child, four days for a married person, as long as half a month for a reigning chief. A paternal relative of the deceased makes the mourning fire.",
    who: "Clan, household, the he-gona of the deceased",
    when: "From death through the mourning period",
    where: "Homestead and burial place",
    why: "The fire is a sign that there is life after death.",
    sources: ["rituals"],
    image: "/media/homestead.jpg",
    tone: "ash",
  },
  {
    id: "healing",
    title: "The healing ceremony",
    collection: "lifecycle",
    status: "unspecified",
    summary:
      "For a serious ailment, illness is answered in ceremony led by traditional healers. The sick person is understood to be troubled by maternal or paternal ancestors. The full procedure stays with the author.",
    who: "Traditional healers, the sick person, kin",
    when: "When a serious illness does not lift",
    where: "Homestead",
    why: "To answer the ancestors behind the illness.",
    sources: ["rituals"],
    image: "/media/mopane.jpg",
    tone: "moss",
  },
  {
    id: "new-house",
    title: "Moving into a new house",
    collection: "lifecycle",
    status: "unspecified",
    summary:
      "Twigs of omugolo are strewn so happiness will reign. A paternal relative throws leaves of omusati with a prayer for peace. The father’s sister may plant omugolo sticks on each side of the entrance.",
    who: "House owner, paternal kin, father’s sister",
    when: "When a homestead is raised or entered",
    where: "New dwelling and its entrance",
    why: "A house is blessed before it is merely occupied.",
    sources: ["rituals", "ethnobotany"],
    image: "/media/homestead.jpg",
    tone: "sand",
  },

  // ── Homestead ────────────────────────────────────────────────────────────
  {
    id: "eelo",
    title: "The main entrance",
    osh: "Eelo / onhu",
    collection: "homestead",
    status: "unspecified",
    summary:
      "The main gate in the palisade faces east, toward prosperity, and commoners enter here. A visiting king, in the old account, does not: he comes in through etambo, the small passage from the kitchen to the granaries.",
    who: "Everyone who approaches the house",
    when: "Daily, and on formal visits",
    where: "Eastern side of the palisade",
    why: "Direction and rank are built into the gate.",
    sources: ["homestead"],
    image: "/media/homestead.jpg",
    tone: "sand",
    mapPoint: {
      x: 92,
      y: 55.5,
      basis: "The passage on the east side of the drawing, by its compass. The source says the main gate faces east.",
    },
  },
  {
    id: "oshoto",
    title: "The meeting fire",
    osh: "Oshinyanga / oshoto / olupale",
    collection: "homestead",
    status: "unspecified",
    summary:
      "At least three meeting places. The main fire sits opposite the senior wife’s room, kept burning for protection and for the tie to the ancestors. Brides and grooms are blessed here. Soldiers have their own place, oshoto shiita.",
    who: "Household, guests, herders",
    when: "Daily, and before journeys or marriage",
    where: "Inside the palisade",
    why: "Story, play, and blessing share one fire.",
    sources: ["homestead"],
    image: "/media/hearth.jpg",
    tone: "clay",
  },
  {
    id: "elugo",
    title: "The kitchen",
    osh: "Epata / elugo",
    collection: "homestead",
    status: "unspecified",
    summary:
      "Three clay stands, omasiga, hold the pot. The staple is oshithima. If a child dies, one stand is replaced. The flour pot must not stand empty, or those at the cattle post are believed to meet hunger.",
    who: "Those who cook for the household",
    when: "Every cooking day",
    where: "Elugo, beside the pantry",
    why: "The kitchen feeds the living and watches over those away.",
    sources: ["homestead"],
    image: "/media/hearth.jpg",
    tone: "ochre",
  },
  {
    id: "osakalwa",
    title: "The birthing hut",
    osh: "Osakalwa",
    collection: "homestead",
    status: "unspecified",
    summary:
      "Near labour the mother moves here with the midwife. The baby is cleaned with red ochre and fat, the cord is tied, and the child is seated on a sifting basket, ongalo, for luck.",
    who: "Mother and midwife",
    when: "Labour and birth",
    where: "Osakalwa",
    why: "Birth is given its own room and its own attendant.",
    sources: ["homestead"],
    image: "/media/hearth.jpg",
    tone: "dusk",
  },
  {
    id: "oshigunda",
    title: "The cattle kraal",
    osh: "Oshigunda",
    collection: "homestead",
    status: "unspecified",
    summary:
      "The kraal is divided into sections for cows, bulls, calves, goats, and sheep. Omugolo may be planted in a new pen so the herd gathers and returns.",
    who: "Herders and the head of the house",
    when: "Daily, and when the herd moves to the cattle post",
    where: "Oshigunda",
    why: "Livestock is the household’s store of life.",
    sources: ["homestead", "ethnobotany"],
    image: "/media/kraal.jpg",
    tone: "clay",
    mapPoint: { x: 76, y: 56, basis: "The enclosures where the drawing shows cattle and goats." },
  },

  // ── Marriage ─────────────────────────────────────────────────────────────
  {
    id: "exogamy",
    title: "One does not marry one’s clan",
    collection: "marriage",
    status: "unspecified",
    summary:
      "Aawambo are generally exogamous. A person of the Aakwanambwa clan does not marry another of that clan, even across ethnic lines. Clan membership makes you kin.",
    who: "Both families",
    when: "Before any union is agreed",
    where: "Across homesteads",
    why: "Marriage should extend kinship, not fold it inward.",
    sources: ["marriage"],
    image: "/media/basket.jpg",
    tone: "ochre",
  },
  {
    id: "preferential",
    title: "Preferred and discouraged partners",
    collection: "marriage",
    status: "fading",
    statusBasis: "In modern times, marriage among cross cousins is rare.",
    summary:
      "The record distinguishes unions that strengthen the system from unions that disorder it. Cross-cousin paths differ by subtribe: some favoured them to keep cattle from going away; Aakwanyama have been wary of cross-cousin marriage on the mother’s side.",
    who: "Families in negotiation",
    when: "At betrothal",
    where: "Both houses",
    why: "Who you may marry is a map of the clan.",
    sources: ["kinship", "marriage"],
    image: "/media/marula.jpg",
    tone: "sand",
  },
  {
    id: "wedding",
    title: "Marriage, old and new together",
    collection: "marriage",
    status: "living",
    statusBasis:
      "Wearing t-shirts and headdresses sporting clan emblem is becoming a common occurrence during the wedding ceremony among Aawambo",
    summary:
      "The ritual record treats a modern-and-traditional wedding as its own ceremony, with banns read in church and flags hoisted at the bride’s home. The marriage paper notes clan emblems on t-shirts and headdresses at today’s weddings.",
    who: "Couple, both families, community",
    when: "The appointed days",
    where: "Homesteads and church",
    why: "A wedding seats two houses, not only two people.",
    sources: ["rituals", "marriage"],
    image: "/media/homestead.jpg",
    tone: "clay",
  },

  // ── Kinship ──────────────────────────────────────────────────────────────
  {
    id: "aakwetu",
    title: "Close, distant, and named kin",
    osh: "Aakwetu",
    collection: "kinship",
    status: "unspecified",
    summary:
      "Relatives are graded by distance: close maternal kin, more distant cousins, and clan-mates whose common ancestor is no longer known. The distant labels are often left out of conversation because they can be heard as slighting.",
    who: "Anyone addressing family",
    when: "In speech, every day",
    where: "Homestead and gathering",
    why: "The word you use tells the distance of blood.",
    sources: ["kinship"],
    image: "/media/basket.jpg",
    tone: "dusk",
  },
  {
    id: "address",
    title: "Tate, meme, tatekulu, meekulu",
    collection: "kinship",
    status: "unspecified",
    summary:
      "Father, mother, grandfather, grandmother — with kuku beside them, and a mother’s brother who may himself be called meme. The terms differ slightly in Oshimbadja, Oshimbaanhu, and Oshikwanyama, which the author treats separately.",
    who: "Children and adults in address",
    when: "Whenever kin are named",
    where: "All dialects, with Oshimbadja, Oshimbaanhu, and Oshikwanyama noted apart",
    why: "Respect is grammatical.",
    sources: ["kinship"],
    image: "/media/basket.jpg",
    tone: "ash",
  },
  {
    id: "clan-father",
    title: "The clan father",
    collection: "kinship",
    status: "unspecified",
    summary:
      "The head of a clan is not only a genealogical point. The sources call him ongudhi yezimo, the pillar of the clan, and shimutsikeni, the arbitrator who settles conflict within the family.",
    who: "Clan head and clanspeople",
    when: "In dispute and counsel",
    where: "Within the clan",
    why: "A clan needs a person who can speak for it.",
    sources: ["kinship"],
    image: "/media/kraal.jpg",
    tone: "clay",
  },

  // ── Plants ───────────────────────────────────────────────────────────────
  {
    id: "omugolo",
    title: "Omugolo, the tree of return",
    osh: "Omugolo",
    collection: "plants",
    status: "unspecified",
    summary:
      "Terminalia sericea. The name comes from gooloka, to return. Travellers inhale its smoke so they come home. Twigs bless a new house. Bark rings a newborn. Hunters, herders, and the sick all meet this tree.",
    who: "Household, travellers, healers",
    when: "Before a journey, at a birth, in illness",
    where: "Reception area, new house, forest",
    why: "Return, luck, and recovery are one idea.",
    sources: ["ethnobotany"],
    image: "/media/mopane.jpg",
    tone: "moss",
  },
  {
    id: "omusati",
    title: "Omusati, the mopane",
    osh: "Omusati",
    collection: "plants",
    status: "unspecified",
    summary:
      "The name is remembered as “what the deceased once said” — a tree whose first name was forgotten. Its leaves are strewn in a new dwelling with a prayer for peace, and in modern times it is important at Christmas.",
    who: "Paternal relatives of the owner",
    when: "When a house is built; at Christmas",
    where: "New dwelling",
    why: "The mopane asks harmony into the walls.",
    sources: ["ethnobotany"],
    image: "/media/mopane.jpg",
    tone: "moss",
  },
  {
    id: "omboga",
    title: "Ekaka and omboga",
    collection: "plants",
    status: "unspecified",
    summary:
      "Leafy food as a sign of happiness, unity, and progress — not only nutrition. Dried spinach kept under the flour is believed to guard family members who are away.",
    who: "Cooks and the household",
    when: "In season, and in storage",
    where: "Fields and elimba, the pantry",
    why: "Greens tie the pot to the people on the road.",
    sources: ["ethnobotany", "homestead"],
    image: "/media/marula.jpg",
    tone: "ochre",
  },

  // ── Greetings ────────────────────────────────────────────────────────────
  {
    id: "morning",
    title: "Greetings through the day",
    collection: "greetings",
    status: "unspecified",
    summary:
      "The day is cut into speech: morning to about nine, late morning to eleven, afternoon, and evening. Each window has its own greeting.",
    who: "Anyone who meets another",
    when: "From dawn through evening",
    where: "Wherever people meet",
    why: "Time of day is part of respect.",
    sources: ["greetings"],
    image: "/media/homestead.jpg",
    tone: "sand",
  },
  {
    id: "visitor",
    title: "Greeting a visitor, and the one who returns",
    collection: "greetings",
    status: "unspecified",
    summary:
      "A visitor the house does not know waits in the ehale, the passage yard, until someone comes out to greet them. Someone back from a long absence is asked: Mwa galuka? — Are you back? — and then whether they have come back safely.",
    who: "Host and guest",
    when: "On arrival and on return",
    where: "Ehale and meeting place",
    why: "The threshold needs its own words.",
    sources: ["greetings"],
    image: "/media/homestead.jpg",
    tone: "ash",
  },
  {
    id: "royal-greet",
    title: "Royal house and ceremony",
    collection: "greetings",
    status: "unspecified",
    summary:
      "The author’s greeting study separates ordinary speech from ceremony, from the royal house, and from the poetic register people use when ordinary words are not enough.",
    who: "Subjects, hosts, speakers",
    when: "Court and ceremony",
    where: "Royal homestead and ritual ground",
    why: "Rank changes the sentence.",
    sources: ["greetings"],
    image: "/media/kraal.jpg",
    tone: "dusk",
  },
];

export const books: Book[] = [
  {
    id: "ando-okwa-li-ihe",
    priceNad: 350,
    title: "Ando okwa li ihe to shanga opo waa dhimbwe",
    subtitle: "Omuthigululwakalo gwAawambo ohela nonena",
    year: 2021,
    publisher: "Namtranslations Services cc",
    language: "Oshiwambo",
    category: "Culture",
    featured: true,
    cover: `${ANDO}/08-front-cover-card.webp`,
    details: {
      titleOnCover: "ANDO OKWA LI IHE TO SHANGA OPO WAA DHIMBWE",
      author: "Petrus Angula Mbenzi",
      publisherFull: "Namtranslations Services cc",
      place: "Windhoek",
      printer: "Microwide Publishing Press",
      isbn: "9789994552320",
      illustrators: "Max Shimi and Kashindi Asuiku",
      front: {
        src: `${ANDO}/01-front-cover.webp`, width: 1135, height: 1600,
        alt: "Front cover: the title over a drawn plan of a homestead with numbered places, a compass rose, and a woman carrying a clay pot.",
        caption: "Front cover",
      },
      back: {
        src: `${ANDO}/06-back-cover.webp`, width: 1200, height: 1600,
        alt: "Back cover: title, a short description in Oshiwambo, and an illustration of a woman pounding grain beside two seated men.",
        caption: "Back cover",
      },
      lookInside: [
        { src: `${ANDO}/02-title-page.webp`, width: 1105, height: 1600, alt: "Title page with the title, subtitle, and author’s name.", caption: "Title page" },
        { src: `${ANDO}/04-dedication.webp`, width: 1107, height: 1600, alt: "Dedication page headed Ohapu yetumba.", caption: "Ohapu yetumba — the dedication" },
        { src: `${ANDO}/05-contents-i.webp`, width: 1094, height: 1600, alt: "First page of the contents, headed Oshikalimo.", caption: "Oshikalimo — contents, page i" },
      ],
      colophon: {
        src: `${ANDO}/03-colophon.webp`, width: 1020, height: 1600,
        alt: "Colophon page with printer, publisher, year, ISBN, and illustrators.",
        caption: "Colophon",
      },
      homesteadMap: {
        src: `${ANDO}/07-homestead-map.webp`, width: 1365, height: 1400,
        alt: "The homestead plan from the front cover: a palisaded homestead with huts, granaries, and cattle enclosures, each place numbered.",
        caption: "The homestead drawn on the cover",
      },
    },
    blurb: "The life of the Aawambo, past and present. This platform is the doorway into that book.",
  },
  {
    id: "b2026a",
    priceNad: 320,
    title: "Omagongo omagongololamwenyo",
    subtitle: "Oshilonga shomagongo mokati kAawambo",
    year: 2026,
    publisher: "Microwide Publishing",
    language: "Oshiwambo",
    category: "Culture",
    featured: false,
    blurb: "Traditional beer and its work among the Aawambo.",
  },
  {
    id: "b2026b",
    priceNad: 320,
    title: "Okumita nokumitika eyono?",
    subtitle: "Onkalo yokumita nokumitika mokati kAawambo ohela nonena",
    year: 2026,
    publisher: "Microwide Publishing",
    language: "Oshiwambo",
    category: "Culture",
    featured: false,
    blurb: "Pregnancy and birth, then and now.",
  },
  {
    id: "b2026c",
    priceNad: 320,
    title: "Omayeletumbulo gOshiwambo",
    subtitle: "A dictionary of sayings and their English equivalents",
    year: 2026,
    publisher: "Microwide Publishing",
    language: "Oshiwambo / English",
    category: "Language",
    featured: false,
    blurb: "Sayings, with English beside them.",
  },
  {
    id: "totem",
    priceNad: 380,
    title: "Totemism and clan system as a world phenomenon",
    subtitle: "The case of Namibia",
    year: 2023,
    publisher: "Microwide Publishing",
    language: "English",
    category: "Clans",
    featured: false,
    blurb: "With L. D. Lumbu. Clans and totems, set in a wider world.",
  },
  {
    id: "dumeni-osh",
    priceNad: 280,
    title: "Etumo nali tu faalele",
    subtitle: "Bishop Kleopas Dumeni, 1973–2017",
    year: 2022,
    publisher: "Microwide Publishing",
    language: "Oshiwambo",
    category: "Biography",
    featured: false,
    blurb: "The footprints of Bishop Kleopas Dumeni.",
  },
  {
    id: "hosianna",
    priceNad: 250,
    title: "Ombuto yokomandongo muushimba",
    subtitle: "The Hosianna congregation in Windhoek",
    year: 2022,
    publisher: "Microwide Publishing",
    language: "Oshiwambo",
    category: "History",
    featured: false,
    blurb: "With J. Fikeipo.",
  },
  {
    id: "liberty",
    priceNad: 300,
    title: "A call for liberty and justice from the pulpit",
    subtitle: "The biography of Kleopas Hafeni Dumeni",
    year: 2021,
    publisher: "Microwide Publishing",
    language: "English",
    category: "Biography",
    featured: false,
    blurb: "A life spoken from the pulpit.",
  },
  {
    id: "medical",
    priceNad: 280,
    title: "Oshiwambo–English Medical Dictionary & Phrasebook",
    year: 2019,
    publisher: "Namtranslations Services",
    language: "Oshiwambo / English",
    category: "Language",
    featured: false,
    blurb: "Words for the clinic.",
  },
  {
    id: "quotes",
    priceNad: 150,
    title: "Notable quotes by Bishop Kleopas Dumeni",
    year: 2016,
    publisher: "Solitaire Press",
    language: "English",
    category: "Biography",
    featured: false,
    blurb: "Lines worth keeping.",
  },
  {
    id: "surnames",
    priceNad: 220,
    title: "A Dictionary of Oshiwambo Surnames",
    year: 2007,
    publisher: "ELCIN Press",
    language: "Oshiwambo / English",
    category: "Language",
    featured: false,
    blurb: "Names and where they come from.",
  },
  {
    id: "school",
    priceNad: 180,
    title: "Oshindonga–English Dictionary for Primary School",
    subtitle: "With O. N. Iithete",
    year: 1995,
    publisher: "Out of Africa Publishers",
    language: "Oshindonga / English",
    category: "Language",
    featured: false,
    blurb: "A first dictionary for learners.",
  },
];
