/**
 * Generates supabase/seed.sql from packages/content/src/catalog.ts.
 * Seeds teasers only: body_md stays null until the professor releases a section.
 *   node --experimental-strip-types scripts/generate-seed.ts
 */
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { books, collections, entries, sources } from "../packages/content/src/catalog.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const q = (v: unknown): string => {
  if (v === undefined || v === null || v === "") return "null";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  if (Array.isArray(v)) return `array[${v.map(q).join(", ")}]::text[]`;
  return `'${String(v).replace(/'/g, "''")}'`;
};
const row = (vals: unknown[]) => `  (${vals.map(q).join(", ")})`;

const out: string[] = [
  "-- Generated by scripts/generate-seed.ts. Do not edit by hand.",
  `-- ${new Date().toISOString().slice(0, 10)} · ${collections.length} collections, ${entries.length} entries, ${books.length} books`,
  "begin;",
  "truncate public.media_assets, public.entries, public.collections, public.books;",
  "",
  "insert into public.collections (slug, title, title_osh, summary, source_file, source_count, source_unit, cover_path, tone, sort_order) values",
  collections
    .map((c, i) =>
      row([c.slug, c.title, c.osh, c.blurb, sources[c.source].file, c.sourceCount?.n, c.sourceCount?.unit, c.image, c.tone, i]),
    )
    .join(",\n") + ";",
  "",
  "insert into public.entries (id, collection_slug, title, title_osh, status, status_basis, summary, who, when_text, where_text, why, sources, image_path, tone, map_x, map_y, map_basis, map_provisional, sort_order, published) values",
  entries
    .map((e, i) =>
      row([e.id, e.collection, e.title, e.osh, e.status, e.statusBasis, e.summary, e.who, e.when, e.where, e.why, e.sources, e.image, e.tone, e.mapPoint?.x, e.mapPoint?.y, e.mapPoint?.basis, e.mapPoint?.provisional ?? false, i, true]),
    )
    .join(",\n") + ";",
  "",
  "insert into public.books (id, title, subtitle, year, publisher, language, category, blurb, featured, buy_url, price_nad, cover_path, sort_order) values",
  books
    .map((b, i) => row([b.id, b.title, b.subtitle, b.year, b.publisher, b.language, b.category, b.blurb, b.featured, b.buyUrl, b.priceNad, b.cover, i]))
    .join(",\n") + ";",
  "",
  "commit;",
  "",
];

writeFileSync(resolve(root, "supabase/seed.sql"), out.join("\n"));
console.log(`Wrote supabase/seed.sql`);
